Traceback (most recent call last):
  File "./bin/runProtagger.py", line 158, in <module>
    Acceptor1 = localpdb(pdb_acceptor)
  File "/beebylab/home/louie/Documents/Code_stuff/test/Protagger_200603/Protagger/bin/localpdb.py", line 7, in localpdb
    acceptor = parser.get_structure(pdb_acceptor,"./"+pdb_acceptor+".pdb")
  File "/usr/local/lib/python2.7/dist-packages/Bio/PDB/PDBParser.py", line 85, in get_structure
    with as_handle(file, mode='rU') as handle:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/Bio/File.py", line 113, in as_handle
    with open(handleish, mode, **kwargs) as fp:
IOError: [Errno 2] No such file or directory: './Campy_FliGM_cring.pdb.pdb'
